baseURL: https://example.com/
title: Solerize
# multilingual config
defaultContentLanguage: en
defaultContentLanguageInSubdir: true

# taxonomies
taxonomies:
  tag: tags
  category: categories
  author: authors
  
# multilingual 404 page config
server:
  headers: null
  redirects:
    - from: /**
      status: 404
      to: /en/404.html

# image caching
caches:
  images:
    dir: :cacheDir/images

# build config for tailwind css
build:
  buildStats:
    enable: true
  cachebusters:
    - source: assets/notwatching/hugo_stats\.json
      target: css
    - source: (postcss|tailwind)\.config\.js
      target: css
module:
  mounts:
    - source: assets
      target: assets
    - disableWatch: true
      source: hugo_stats.json
      target: assets/notwatching/hugo_stats.json
