baseURL: /

# multillingual configs
defaultContentLanguage: en
defaultContentLanguageInSubdir: true


caches:
  images:
    dir: :cacheDir/images

# tailwind specific build commands
build:
  buildStats:
    enable: true
  cachebusters:
    - source: assets/notwatching/hugo_stats\.json
      target: css
    - source: (postcss|tailwind)\.config\.js
      target: css
module:
  mounts:
    - source: assets
      target: assets
    - disableWatch: true
      source: hugo_stats.json
      target: assets/notwatching/hugo_stats.json
